package com.example.core.intelligence.correction

enum class FailureType {
    OCR_FAILURE,
    NORMALIZATION_FAILURE,
    TOKENIZATION_FAILURE,
    EXTRACTION_FAILURE,
    ALIAS_FAILURE,
    CANONICALIZATION_FAILURE,
    LOW_CONFIDENCE_FAILURE,
    TRUNCATION_FAILURE,
    NOISE_FAILURE,

    // Stage 6: Semantic correction failures
    FUZZY_CORRECTION_FAILURE,
    UNKNOWN_INGREDIENT_FAILURE,
    AMBIGUOUS_MATCH_FAILURE,
    LOW_CONFIDENCE_CORRECTION_FAILURE,

    // Stage 6.5: Semantic expansion failures
    GROUPING_FAILURE,
    CONTEXT_DISAMBIGUATION_FAILURE,
    PHRASE_CORRECTION_FAILURE,
    NESTED_STRUCTURE_FAILURE
}
